/**
 * Sample Video Database
 */
export var videoDatabase =
  [
    {
      id: 'MV002527780000',
      name: 'Iron Man 2',
      contentType: 'ON_DEMAND',
      videoUrl: 'elephants-dream/Elephants.Dream.mp4',
      actors: ['Robert Downey Jr.', 'Gwyneth Paltrow', 'Don Cheadle'],
      genre: ['Action', 'Adventure', 'Highly Rated', 'Recommended Movies'],
      thumbnailImageDescription: 'Iron Man 2',
      thumbnailImageSources: [
        {
          url: 'elephants-dream/Elephants.Dream.thumbnail.jpg',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2010',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 634000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      closedCaptionsFile: 'elephants-dream/Elephants.Dream.cc.vtt',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '663642',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.0',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV009844570000',
      name: 'The Commuter',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Liam Neeson', 'Vera Farmiga', 'Patrick Wilson'],
      genre: ['Action', 'Highly Rated', 'Recommended Movies'],
      thumbnailImageDescription: 'The Commuter',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2018',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '84823',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.3',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'SH030762300000S1E1',
      name: 'Good Omens',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy', 'Popular TV Shows'],
      thumbnailImageDescription: 'Good Omens',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'In the Beginning',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '28413',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.3',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH030762300000S1E2',
      name: 'Good Omens',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Good Omens',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '2',
      episodeName: 'The Book',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '28413',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.3',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH030762300000S1E3',
      name: 'Good Omens',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Good Omens',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '3',
      episodeName: 'Hard Times',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '28413',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.3',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH030762300000S1E4',
      name: 'Good Omens',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Good Omens',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '4',
      episodeName: 'Saturday Morning Funtime',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '28413',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.3',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH030762300000S1E5',
      name: 'Good Omens',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Good Omens',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '5',
      episodeName: 'The Doomsday Option',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '28413',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.3',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH030762300000S1E6',
      name: 'Good Omens',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Good Omens',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '6',
      episodeName: 'The Very Last Day of the Rest of Their Lives',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '28413',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.3',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S1E1',
      name: 'Law & Order: Special Victims Unit',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'Payback',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2000',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S1E2',
      name: 'Law & Order: Special Victims Unit',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '2',
      episodeName: 'A Single Life',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2000',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S1E3',
      name: 'Law & Order: Special Victims Unit',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '3',
      episodeName: 'Or Just Look Like One',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2000',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S1E4',
      name: 'Law & Order: Special Victims Unit',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '4',
      episodeName: 'Hysteria',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2000',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S1E5',
      name: 'Law & Order: Special Victims Unit',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '5',
      episodeName: 'Sophomore Jinx',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2000',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S5E1',
      name: 'Law & Order: Special Victims Unit ',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit ',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '5',
      episodeNumber: '1',
      episodeName: 'Tragedy',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2004',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S5E2',
      name: 'Law & Order: Special Victims Unit ',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit ',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '5',
      episodeNumber: '2',
      episodeName: 'Manic',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2004',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S5E3',
      name: 'Law & Order: Special Victims Unit ',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit ',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '5',
      episodeNumber: '3',
      episodeName: 'Mother',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2004',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S5E4',
      name: 'Law & Order: Special Victims Unit ',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit ',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '5',
      episodeNumber: '4',
      episodeName: 'Loss',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2004',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH003169780000S5E5',
      name: 'Law & Order: Special Victims Unit ',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Michael Sheen', 'David Tennant', 'Adria Arjona'],
      genre: ['Adventure', 'Comedy', 'Action', 'Fantasy'],
      thumbnailImageDescription: 'Law & Order: Special Victims Unit ',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '5',
      episodeNumber: '5',
      episodeName: 'Serendipity',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2004',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '69645',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.0',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'MV009782830000',
      name: 'Daddys Home 2',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Will Ferrell', 'Mark Wahlberg', 'Linda Cardellini'],
      genre: ['Comedy'],
      thumbnailImageDescription: 'Daddys Home 2',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2017',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '49701',
      reviewsType: 'FOUR_STAR',
      reviewsRatingDisplayString: '6.0',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV008858190000',
      name: 'Baywatch',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Dwayne Johnson', 'Zac Efron', 'Alexandra Daddario'],
      genre: ['Comedy'],
      thumbnailImageDescription: 'Baywatch',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2017',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '139793',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '5.6',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV010731140000',
      name: 'The Spy Who Dumped Me',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Mila Kunis', 'Kate McKinnon'],
      genre: ['Comedy', 'Action', 'Adventure'],
      thumbnailImageDescription: 'The Spy Who Dumped Me',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2018',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '51628',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.0',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV001488420000',
      name: 'Soul Plane',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Godfrey', 'MoNique', 'Arielle Kebbel'],
      genre: ['Comedy'],
      thumbnailImageDescription: 'Soul Plane',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2004',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '20501',
      reviewsType: 'THREE_STAR',
      reviewsRatingDisplayString: '4.5',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'EP030617915018',
      name: 'Overboard',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Eugenio Derbez', 'Anna Faris', 'Eva Longoria'],
      genre: ['Comedy'],
      thumbnailImageDescription: 'Overboard',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2018',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '26564',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.0',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV001979180000',
      name: 'Rush Hour 3',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Chris Tucker', 'Jackie Chan', 'Hiroyuki Sanada'],
      genre: ['Action', 'Adventure', 'Comedy', 'Drama', 'Suspense'],
      thumbnailImageDescription: 'Rush Hour 3',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2007',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '142392',
      reviewsType: 'FOUR_STAR',
      reviewsRatingDisplayString: '6.2',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV003389570000',
      name: 'No Strings Attached',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Natalie Portman', 'Ashton Kutcher', 'Kevin Kline'],
      genre: ['Comedy', 'Highly Rated'],
      thumbnailImageDescription: 'No Strings Attached',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2011',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '198730',
      reviewsType: 'FOUR_STAR',
      reviewsRatingDisplayString: '6.2',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'SH008378340000S1E1',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense', 'Popular TV Shows'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'Pilot',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2007',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S1E2',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense', 'Popular TV Shows'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '2',
      episodeName: 'The Spellingg Bee',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2007',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S1E3',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense', 'Popular TV Shows'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '3',
      episodeName: 'Speak Now or Forever Hold Your Piece',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2007',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S1E4',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense', 'Popular TV Shows'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '4',
      episodeName: 'Woman Seeking Dead Husband, Smokers Okay, No Pets',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2007',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S1E5',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense', 'Popular TV Shows'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '5',
      episodeName: '9 Lives',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2007',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S2E1',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '2',
      episodeNumber: '1',
      episodeName: 'American Duos',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2008',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S2E2',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '2',
      episodeNumber: '2',
      episodeName: 'Sixty Five Million Years Off',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2008',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S2E3',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '2',
      episodeNumber: '3',
      episodeName: 'Psy vs. Psy',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2008',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S2E4',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '2',
      episodeNumber: '4',
      episodeName: 'Zero to Murder in Sixty Seconds',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2008',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH008378340000S2E5',
      name: 'Psych',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['James Roday', 'Dule Hill', 'Timothy Omundson'],
      genre: ['Comedy', 'Suspense'],
      thumbnailImageDescription: 'Psych',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '2',
      episodeNumber: '5',
      episodeName: 'And Down the Stretch Comes Murder',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2008',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '77824',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.4',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'MV000192370000',
      name: 'Clue',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Eileen Brennan', 'Tim Curry', 'Madeline Kahn'],
      genre: ['Comedy', 'Drama', 'Thriller'],
      thumbnailImageDescription: 'Clue',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '1985',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '70088',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.3',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV010013370000',
      name: 'Forever My Girl',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Alex Roe', 'Jessica Rothe', 'Abby Ryder Fortson'],
      genre: ['Drama', 'Romance'],
      thumbnailImageDescription: 'Forever My Girl',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2018',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '10813',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.7',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV002822510000',
      name: 'The Next Three Days',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Russell Crowe', 'Elizabeth Banks', 'Liam Neeson'],
      genre: ['Action', 'Drama', 'Suspense'],
      thumbnailImageDescription: 'The Next Three Days',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2010',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '169038',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.4',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV004135740000',
      name: 'The Frozen Ground',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Nicolas Cage', 'John Cusack', 'Vanessa Hudgens'],
      genre: ['Drama', 'Suspense'],
      thumbnailImageDescription: 'The Frozen Ground',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2013',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '52277',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.4',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'MV000351690000',
      name: 'Patriot Games',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Harrison Ford', 'Anne Archer', 'Patrick Bergin'],
      genre: ['Action', 'Drama', 'Suspense', 'Recommended Movies'],
      thumbnailImageDescription: 'Patriot Games',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '1992',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '94555',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.9',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'SH014189710000S1E1',
      name: 'Grimm',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['David Giuntoli', 'Bitsie Tulloch', 'Russell Hornsby'],
      genre: ['Suspense', 'Drama', 'Horror'],
      thumbnailImageDescription: 'Grimm',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'Grimm Pilot',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2012',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '102882',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.8',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH014189710000S1E2',
      name: 'Grimm',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['DavidGiuntoli', 'BitsieTulloch', 'RussellHornsby'],
      genre: ['Suspense', 'Drama', 'Horror'],
      thumbnailImageDescription: 'Grimm',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '2',
      episodeName: 'Bears Will Be Bears',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2012',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '102882',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.8',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH014189710000S1E3',
      name: 'Grimm',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['DavidGiuntoli', 'BitsieTulloch', 'RussellHornsby'],
      genre: ['Suspense', 'Drama', 'Horror'],
      thumbnailImageDescription: 'Grimm',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '3',
      episodeName: 'BeeWare',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2012',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '102882',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.8',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH014189710000S1E4',
      name: 'Grimm',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['DavidGiuntoli', 'BitsieTulloch', 'RussellHornsby'],
      genre: ['Suspense', 'Drama', 'Horror'],
      thumbnailImageDescription: 'Grimm',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '4',
      episodeName: 'Lonelyhearts',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2012',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '102882',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.8',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH014189710000S1E5',
      name: 'Grimm',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['DavidGiuntoli', 'BitsieTulloch', 'RussellHornsby'],
      genre: ['Suspense', 'Drama', 'Horror'],
      thumbnailImageDescription: 'Grimm',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '5',
      episodeName: 'Danse Macabre',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2012',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '102882',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.8',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'MV000833190000',
      name: 'The Legend of Bagger Vance',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Will Smith', 'Matt Damon', 'Charlize Theron'],
      genre: ['Drama', 'Fantasy'],
      thumbnailImageDescription: 'The Legend of Bagger Vance',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2000',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '50836',
      reviewsType: 'FOUR_STAR',
      reviewsRatingDisplayString: '6.7',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },
    {
      id: 'SH029962980000S1E1',
      name: 'The Rook',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Emma Greenwell', 'Joely Richardson', 'Jon Fletcher'],
      genre: ['Drama', 'Fantasy', 'Suspense'],
      thumbnailImageDescription: 'The Rook',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'Chapter 1',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '914',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.5',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH029962980000S1E2',
      name: 'The Rook',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Emma Greenwell', 'Joely Richardson', 'Jon Fletcher'],
      genre: ['Drama', 'Fantasy', 'Suspense'],
      thumbnailImageDescription: 'The Rook',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '2',
      episodeName: 'Chapter 2',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '914',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.5',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH029962980000S1E3',
      name: 'The Rook',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Emma Greenwell', 'Joely Richardson', 'Jon Fletcher'],
      genre: ['Drama', 'Fantasy', 'Suspense'],
      thumbnailImageDescription: 'The Rook',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '3',
      episodeName: 'Chapter 3',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '914',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.5',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH029962980000S1E4',
      name: 'The Rook',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Emma Greenwell', 'Joely Richardson', 'Jon Fletcher'],
      genre: ['Drama', 'Fantasy', 'Suspense'],
      thumbnailImageDescription: 'The Rook',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '4',
      episodeName: 'Chapter 4',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '914',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.5',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH029962980000S1E5',
      name: 'The Rook',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Emma Greenwell', 'Joely Richardson', 'Jon Fletcher'],
      genre: ['Drama', 'Fantasy', 'Suspense'],
      thumbnailImageDescription: 'The Rook',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }
      ],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '5',
      episodeName: 'Chapter 5',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2019',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '914',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.5',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },
    {
      id: 'SH002960010000S1E1',
      name: 'Family Guy',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Seth MacFarlane', 'Alex Borstein', 'Mila Kunis'],
      genre: ['comedy'],
      thumbnailImageDescription: 'Family Guy',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'Death Has a Shadow',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '1999',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '285142',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.2',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },

    {
      id: 'SH014986730000',
      name: 'Black Panther',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Chadwick Boseman'],
      genre: ['action', 'Recommended Movies'],
      thumbnailImageDescription: 'Black Panther',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2018',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '527282',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '7.3',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    },

    {
      id: 'SH024519750000S1E1',
      name: 'Stranger Things',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Millie Bobby Brown', 'Natalia Dyer', 'Charlie Heaton'],
      genre: ['fiction', 'Highly Rated', 'Popular TV Shows'],
      thumbnailImageDescription: 'Stranger Things',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'The Vanishing of Will Byers',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2016',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '633460',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.9',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },

    {
      id: 'SH011363840000S1E1',
      name: 'Friends',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow', 'Matt LeBlanc', 'Matthew Perry', 'David Schwimmer'],
      genre: ['comedy', 'Highly Rated', 'Popular TV Shows'],
      thumbnailImageDescription: 'Watch Friends',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      contentDescription: 'series',
      seasonNumber: '1',
      episodeNumber: '1',
      episodeName: 'The One Where Monica Gets a Roommate',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '1994',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '687967',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '8.9',
      ratingCategory: 'G',
      webPlayerContentType: 'TV_SERIES_EPISODE'
    },

    {
      id: 'AMZ#1',
      name: 'Public Broadcasting Service',
      contentType: 'LIVE',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      contentDescription: 'channel',
      actors: [],
      genre: [],
      networkDetails:
        {
          callSign: 'PBS',
          affiliateCallSign: 'KCTS9',
          isLiveBroadcast: 'true',
          end: '2050-07-23T02:30:00Z',
          start: '2010-07-24T00:00:00Z',
          channelName: 'PBS'
        },
      webPlayerContentType: 'VIDEO'
    },

    {
      id: 'AMZ#2',
      name: 'National Broadcasting Company',
      contentType: 'RECORDING',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      contentDescription: 'channel',
      actors: [],
      genre: [],
      networkDetails:
        {
          callSign: 'NBC',
          affiliateCallSign: 'KCTS9',
          isLiveBroadcast: 'false',
          end: '2050-07-23T02:30:00Z',
          start: '2010-07-24T00:00:00Z',
          channelName: 'NBC'
        },
      webPlayerContentType: 'VIDEO'

    },

    {
      id: 'MV006823950000',
      name: 'The Transporter',
      contentType: 'ON_DEMAND',
      videoUrl: 'big-buck-bunny/Bug.Buck.Bunny.mp4',
      actors: ['Jason Statham', 'Qi Shu', 'Matt Schulze'],
      genre: ['action', 'thriller', 'Recommended Movies'],
      thumbnailImageDescription: 'The Transporter',
      thumbnailImageSources: [
        {
          url: 'big-buck-bunny/Big.Buck.Bunny.thumbnail.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      contentDescription: 'movie',
      parentalControl: 'NOT_REQUIRED',
      absoluteViewingPositionMilliseconds: '0',
      itemType: 'VIDEO',
      releaseYear: '2002',
      selectionAction: 'PLAY',
      runTimeInMilliseconds: 635000,
      runTimeDisplayString: '9m',
      closedCaptionStatus: 'AVAILABLE',
      closedCaptionDisplayString: 'CC',
      viewingDisplayString: 'Play Now',
      reviewsTotalReviewCount: '270594',
      reviewsType: 'FIVE_STAR',
      reviewsRatingDisplayString: '6.8',
      ratingCategory: 'G',
      webPlayerContentType: 'VIDEO'
    }
  ]

// Sample Landing Page Categories Database
export var categoryDatabase =
  [
    {
      name: 'Highly Rated',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Highly Rated Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/default-category.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/highlyRated'
    },

    {
      name: 'Recommended Movies',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Recommended Movies Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/default-category.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/recommendedMovies'
    },

    {
      name: 'Popular TV Shows',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Popular TV Shows Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/default-category.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/popularTvShows'
    },
    {
      name: 'Comedy',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Comedy Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/Comedy.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/comedy'
    },
    {
      name: 'Action',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Action Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/Action.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/action'
    },
    {
      name: 'Fiction',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Fiction Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/Fiction.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/fiction'
    },
    {
      name: 'Drama',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Drama Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/Drama.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/drama'
    },
    {
      name: 'Adventure',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Adventure Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/Adventure.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/adventure'
    },
    {
      name: 'Thriller',
      contentType: 'ON_DEMAND',
      itemType: 'CATEGORY',
      selectionAction: 'BROWSE',
      thumbnailImageDescription: 'Thriller Image',
      thumbnailImageSources: [
        {
          url: 'https://vsk-multi-modal-demo-content.s3.amazonaws.com/skill-assets/Thriller.png',
          size: 'SMALL',
          widthPixels: 720,
          heightPixels: 480
        }],
      id: 'entity://provider/category/thriller'
    }
  ]

// Sample device Capabilities
export var capabilitiesDatabase =
  [
    {
      endpointId: 'ALEXA_VOICE_SERVICE_EXTERNAL_MEDIA_PLAYER_VIDEO_PROVIDER',
      endpointTypeId: 'TEST_VSK_MM',
      manufacturerName: 'TEST_VSK_MM',
      friendlyName: 'TEST_VSK_MM',
      description: 'TEST_VSK_MM',
      displayCategories: ['APPLICATION'],
      cookie: {},
      capabilities: [
        {
          type: 'AlexaInterface',
          interface: 'Alexa.RemoteVideoPlayer',
          version: '1.0'
        }, {
          type: 'AlexaInterface',
          interface: 'Alexa.PlaybackController',
          version: '1.0'
        }, {
          type: 'AlexaInterface',
          interface: 'Alexa.SeekController',
          version: '1.0'
        }, {
          type: 'AlexaInterface',
          interface: 'Alexa.ChannelController',
          version: '1.0'
        },
        {
          type: 'AlexaInterface',
          interface: 'Alexa.MultiModalLandingPage',
          version: '1.0'
        }
      ]
    }
  ]
