/**
 * An enum for events that can be triggered by Alexa
 */
export const AlexaEvent = {
  LOAD_CONTENT: 'LOAD_CONTENT',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',
  NEXT: 'NEXT',
  PREVIOUS: 'PREVIOUS',
  SET_SEEK_POSITION: 'SET_SEEK_POSITION',
  ADJUST_SEEK_POSITION: 'ADJUST_SEEK_POSITION',
  CLOSED_CAPTIONS_STATE_CHANGE: 'CLOSED_CAPTIONS_STATE_CHANGE',
  PREPARE_FOR_CLOSE: 'PREPARE_FOR_CLOSE',
  ACCESS_TOKEN_CHANGE: 'ACCESS_TOKEN_CHANGE'
}
